### ISSUE TITLE
Add the ability to view local branches sorted by most recently committed

### ISSUE THREAD

**Issue by drewbrokke** [jwu910/check-it-out#115]
I use a custom git command quite often called `git recent` which is an alias for this command:

```
for-each-ref --count=20 --sort=-committerdate refs/heads/ --format="%(refname:short)"
```

I think this tool could be very useful for quickly browsing between recently used branches.

**Comment by jwu910** [comment]
Hi Drew, the default view when calling Check It Out should be your local branches and sorted by committer date.. If it's not, something's terribly wrong lol. I'm actually calling for-each-ref to populate my branch information, but I may have to look at the options you're passing in and maybe I can manipulate how im using `for-each-ref` to get some better performance on larger projects.

**Comment by jwu910** [comment]
Closing as refs are already sorted by recent commits. Thanks!
