### ISSUE TITLE
Workflow: Keep contributor commit history

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#145]
I have been currently squashing and merging my feature branches into my development to help maintain some cleaner code. I just realized that while doing this, I may lose some individual commits from other contributors.

How can I maintain a clean commit history while still giving credit to the contributor?

Todo: Research some other project workflows

**Comment by rainrivas** [comment]
@jwu910 are you sure that users are losing their little green boxes? I think they would lose their "blame" but would still have the green box. Also, since it's all forked, their fork should show that their code got merged in "PR ##"

**Comment by jwu910** [comment]
@rainrivas Oh. That's a good point... I'll have to dig in a little more. I think you're right they keep the green squares if the code gets merged. 

If this is the case, Is keeping the blame the question I need to answer then. I would like for their names to show up as a contributor on the repo information.

**Comment by jwu910** [comment]
I was advised to squash the PR w/o putting in more work. If additional work was required, either merge it and create a ticket, or have the contributor make the changes before the PR is accepted. This should preserve the blame so contributor is attributed with the ticket they helped with.

**Comment by rainrivas** [comment]
@jwu910 and if you're squashing into dev and merge-commit into master it should preserve those logs too

**Comment by jwu910** [comment]
@rainrivas I think my issue was that I was pulling the PR down and making adjustments prior to squashing it into development. Will ask for changes or create a new issue moving forward.
