### ISSUE TITLE
Documentation: Contributors again?

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#147]
Adding all-contributors package will require quite a bit of work to maintain and update contributors if the list gets larger. Is there an automated method that generates the contributor list?

~I particularly am fond of the styles the list VueJS has on their project.
https://github.com/vuejs/vue~

**Comment by jwu910** [comment]
Should we just link to the contributors' section? I like having images for users that contribute to the project.

All-contributors package is nice because I can add users who contribute outside of code. If the list can grow on its own, that'd be awesome.

**Comment by jwu910** [comment]
https://developer.github.com/v3/repos/#list-contributors

Hit the GH api for contributors? Somehow generate a markdown block we add to readme automatically?

**Comment by rainrivas** [comment]
@jwu910 i gotchu
```cURL
curl -X GET \
  http://api.github.com/repos/jwu910/check-it-out/contributors \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 330b7c62-1c4c-44e2-ba48-14f008b653ca'
```
