### ISSUE TITLE
Update version requirements

### ISSUE THREAD

**Issue by vutran** [jwu910/check-it-out#179]
Version requirements are inconsistent

- README (>= 6.0)
- package.json (>= 7)
- .babelrc (targets node 4) -- could probably just remove the transpiling step

**Comment by jwu910** [comment]
Hi @vutran #177 Updated the documentation

It's in development now, but not yet in master.

**Comment by jwu910** [comment]
https://github.com/jwu910/check-it-out/pull/182 Thanks!
