### ISSUE TITLE
Pretty Formatting Log

### ISSUE THREAD

**Issue by excalith** [jwu910/check-it-out#193]
Currently log uses a lot of space, making it hard to _check it out_. I believe it would be better to format log output to display commits line by line. I have already cloned and made that change, if you think this is useful I can send PR.

**Comment by jwu910** [comment]
Hi! Thanks for opening this issue. I wanted to leave the default log in place, but also add in the ability for a user to configure their log.

I had #102 open to hopefully achieve this sometime. 

My idea was to let users just add in a list of custom arguments they could pass into git log that would be called any time they utilized the `[space]` functionality.

What do you think?

**Comment by excalith** [comment]
Did not realize that issue was related to log as well, sorry about that. Config functionality sounds great, but storing and reading it in different OSes is - as far as I know - is something else. I have seen a module https://github.com/lorenwest/node-config might come in handy for configs. Do you want me to take a look into it? Tho I only have Windows, will require nix tests

**Comment by jwu910** [comment]
Not an issue, however have you been able to get it working on windows? Lol! I have some tickets open for problems running this on git bash and powershell. I don't develop on my windows machine much and haven't been able to figure it out.

I am definitely open to looking at a package to help. I was debating on setting up a dot env file rather than have a user edit source, but I'll have to look more into node-config.

**Comment by excalith** [comment]
Well I use ConEmu emulator cmder, tried on git bash to checkout if it was working for me as well, yet it didn't print correct. The rumors were true! Even simplest apps can be troubling with bash on windows lol

Allrighty, I won't send PR for this and take a look at config thing on my spare time as well. If I come up with something good, will let you know at #102 

Btw my friends are in love with this repo, hope I can contribute more cool stuff to it!

**Comment by jwu910** [comment]
Thanks @excalith Those are very kind words! I really hope you can contribute too! I'll close this issue for now and we can continue a discussion on #102 if you have any more questions.

Windows has been pretty frustrating if you get any ideas for #127  or #128, that'd be greatly appreciated as well. Though I think those tickets may be able to be combined...
