### ISSUE TITLE
Feature: Change refresh button to Ctrl + r

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#212]
~While any loading screen is displayed, user is unable to quit Check It Out with the exit keys(<kbd>q</kbd>, <kbd>ctrl</kbd>-<kbd>c</kbd>, <kbd>esc</kbd>)~

Edit:

Revision, Change refresh keys to <kbd>Ctrl</kbd>+<kbd>r</kbd>

Accidentally hitting <kbd>r</kbd> on larger projects can create unecessary wait time for a refresh that will do nothing.

**Comment by jwu910** [comment]
Is this really a problem?

**Comment by jwu910** [comment]
@rainrivas Found out that this is actually intentional...

https://github.com/chjj/blessed/blob/master/lib/widgets/loading.js#L58

This line disables keys while loading is in effect. I need to decide if I want a workaround, or just wont-fix... If I enable keys while loading, There are many cases I need to account for so the app doesn't break...

**Comment by rainrivas** [comment]
@jwu910 i recommend leaving it as is. What's the reason why you would want to quit before loading is done?

**Comment by jwu910** [comment]
@rainrivas Yeah, thinking about it. Maybe we change the refresh function to <kbd>Ctrl</kbd>+<kbd>r</kbd> instead. I've pressed just <kbd>r</kbd> on projects at work unintentionally and some of the larger projects still take a while to refresh.
