### ISSUE TITLE
Add spinner for long running operations

### ISSUE THREAD

**Issue by protoEvangelion** [jwu910/check-it-out#247]
When switching to a branch that has a lot of changes compared to the current branch, it would be nice to see some sort of UI indicator that lets me know that the `check-it-out` process is not frozen. There is a good one in this library: https://github.com/oclif/cli-ux

**Comment by jwu910** [comment]
The blessed widget https://github.com/chjj/blessed/blob/master/lib/widgets/loading.js loading has something like this built in to the dependency Maybe a good idea to take a look to see if we can this can be implemented

**Comment by protoEvangelion** [comment]
https://www.npmjs.com/package/blessed#loading-from-box

**Comment by jwu910** [comment]
@protoEvangelion Yup! Same one, it's currently being used on the refresh command.

**Comment by jwu910** [comment]
Should fix #246
