### ISSUE TITLE
Implement tool to generate gh-pages site and readme

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#249]
We should use

* gatsby-source-filesystem
* gatsby-transformer-remark

We'll setup on master, and gatsby can deploy to gh-pages.

This way, master can be our single source of truth.

http://ricostacruz.com/flatdoc/#flatdoc-getting-started *alternative

**Comment by jwu910** [comment]
Can we store gh-pages source code on master, but deploy to gh-pages?

**Comment by jwu910** [comment]
maybe keep everything in `docs/` ?

**Comment by jwu910** [comment]
https://www.npmjs.com/package/gh-pages will allow us to deploy to a gh-pages branch. We could keep the documentation in the source code since our publish scripts only include the build files.. Wouldn't be an issue.

**Comment by jwu910** [comment]
http://ricostacruz.com/flatdoc/#flatdoc-getting-started Seems like a cool tool

**Comment by TheCoolBlackCat** [comment]
Are you just looking to generate a site based on the `README.md`? I think GitHub pages can do that automagically now. Not sure if I'm missing something... happy to take a look if that would work as Plan A? @jwu910 (hunting for a "good first issue")

**Comment by jwu910** [comment]
> Are you just looking to generate a site based on the `README.md`? I think GitHub pages can do that automagically now. Not sure if I'm missing something... happy to take a look if that would work as Plan A? @jwu910 (hunting for a "good first issue")

Hey @TheCoolBlackCat !

This is a 3y old ticket so I'd have to give this some thought. I def know GitHub pages has changed and grown in the last few years.

I had a separate site mocked up and built on a different branch in this repo, with a CNAME pointing to a custom domain. That domain has since expired and it might be cool to at the very least move that site into a docs/ directory here. GH-pages let's us deploy from directories other than root now as well. That might be the simplest alternative.

Is that something you'd like to take a look at?

**Comment by TheCoolBlackCat** [comment]
> Is that something you'd like to take a look at?


Sure! That sounds like a good start, happy to bring things over into a docs folder so a GH pages site can go live. 

Like I said, I think GH can do most of it for us in a first pass. But happy to look at Jekyll and alternatives for what they offer. I'm used to Hugo (written in Go) but they are all somewhat similar and I assume we would prefer a JS-based one?

Feel free to assign me the issue :)
