### ISSUE TITLE
Initial load screen disappears after a brief display

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#257]
**Actual**: When starting Check It Out in a large project, the initial loading text will display before promptly disappearing for the remainder of the load time.

**Expected**: The loading text should be displayed during the entire load process.

<hr>
I think this has to do with the order of operations that take place during initial start up time. The loading text should persist until we successfully fetch and parse all of our information needed.

This is much easier tested on a large project. 
https://github.com/liferay/liferay-portal
This is a large enough project with years of git refs.

**Note**: Please refer to [Contributing guidelines](https://github.com/jwu910/check-it-out/blob/master/CONTRIBUTING.md) before starting development. Thanks!

**Comment by louillustrator** [comment]
I will take a look :)

**Comment by JayaKrishnaNamburu** [comment]
Hi, I liked the concept behind this and the way it is working and I would like to contribute to this 😄 .  But I have few doubts regarding how to set up and work in development mode. I installed and ran ``npm run watch`` but I am a little confused how the dev commands are tested, I am kind of new to this node environments.

**Comment by jwu910** [comment]
Hi @JayaKrishnaNamburu , I'd be happy to try and help walk you through setting up.

Until I get a test suite set up, local development testing is pretty much all user acceptance testing through manual clicks.

In the project folder you can run `npm link` which will bind the check it out command `cio` and `checkit` to the build files for your local repo. Then when you run Check It Out, it will use the build files from your repo rather than your npm global node_modules directory.

I hope this helps, let me know if you have more questions

**Comment by JayaKrishnaNamburu** [comment]
> Hi @JayaKrishnaNamburu , I'd be happy to try and help walk you through setting up.
> 
> Until I get a test suite set up, local development testing is pretty much all user acceptance testing through manual clicks.
> 
> In the project folder you can run `npm link` which will bind the check it out command `cio` and `checkit` to the build files for your local repo. Then when you run Check It Out, it will use the build files from your repo rather than your npm global node_modules directory.
> 
> I hope this helps, let me know if you have more questions

Thank you @jwu910 will try the process that you suggested 😄

**Comment by JayaKrishnaNamburu** [comment]
Hi, @jwu910 please review the changes. Please let me know if is miss out anything 😅 .

**Comment by jwu910** [comment]
Merged, thanks @JayaKrishnaNamburu !

**Comment by JayaKrishnaNamburu** [comment]
Hi, @jwu910 please let me know if I can help with any other things in the repo. I will be happy to do.

**Comment by jwu910** [comment]
@JayaKrishnaNamburu You can keep an eye on the issues, or star/subscribe to the repo to keep up to date! Thanks again

**Comment by JayaKrishnaNamburu** [comment]
> @JayaKrishnaNamburu You can keep an eye on the issues, or star/subscribe to the repo to keep up to date! Thanks again

sure 👍
