### ISSUE TITLE
User is unable to quit CIO with hotkey q while app is loading

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#259]
If a user is loading a large project, or fetching a project and the process displays the loading window, the user is unable to quit the app. Ctrl+c is also not terminating the current loading process.

A user should be able to press the quit hotkey from any screen on blessed.

Possible location to look: https://github.com/jwu910/check-it-out/blob/master/src/app.js#L89

Maybe we need to add the key listener to the loading screen.

**Comment by 9reeno** [comment]
I'll pick this one up!

**Comment by jwu910** [comment]
@9reeno Go for it, let me know if you have any questions

**Comment by 9reeno** [comment]
Hi! Question already.

index.js requires './dist/app' but the dist directory is on .gitignore in the development branch.

Am I missing something? Thanks.

**Comment by jwu910** [comment]
@9reeno No problem! I kept the dist/ out of the source files, just so it doesnt take up more space.

Maybe I'll have to create another issue for setting up the development environment.

**Comment by 9reeno** [comment]
@jwu910 Got done with classes for today- Got an update for you

Looks like loading.load() blocks all key input until loading.stop() is called [(see blessed.loading docs)](https://github.com/chjj/blessed#loading).

Adding loading.keys(...) in app.js manually does not appear to work.

To fix this, we could consider a keylistener that run separately from blessed. [iohooks](https://www.npmjs.com/package/iohook) and [keypress](https://dmauro.github.io/Keypress/) look like good candidates.

Thoughts? Thanks!

**Comment by jwu910** [comment]
How about an alternative to loading.load() ?

I don’t mind manually displaying a new box to indicate information is being fetched.

Maybe we can avoid adding another dependency since blessed already has key listeners. 

If you want, you can see if you can try replacing the loading screen with something just like a text box and instead of q quitting check it out, see if we can cancel the git process we spawned to fetch.

**Comment by 9reeno** [comment]
Figured out that we could keep the loading screen API if we added just one property to the main screen! I also added the process cancelling you mentioned.
