### ISSUE TITLE
Add first-timers-only badge to readme

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#260]
`[![first-timers-only](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://www.firsttimersonly.com/)`

[![first-timers-only](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://www.firsttimersonly.com/)

Add the first-timers-only badge to readme.

~~Bonus: Add the badge to the gh-pages branch as well.~~

**Comment by devkant** [comment]
Can I claim this?

**Comment by jwu910** [comment]
@devkant Go for it! Let me know if you need anything.

**Comment by devkant** [comment]
Where should I add the badge in gh-pages branch?

**Comment by jwu910** [comment]
@devkant On second thought. Let's actually pass on the badges for the gh-pages. I checked the source again, and saw I only have the github badges for now.

I'll review your PR once I get a chance, thanks!

**Comment by jwu910** [comment]
Closing this per solution from @devkant
