### ISSUE TITLE
Can't Assign PR Reviewer

### ISSUE THREAD

**Issue by rainrivas** [jwu910/check-it-out#270]
Danger expects a PR to have an assigned reviewer, but when opening PRs we cannot assign someone to review. 
*Suggestion* -- Make Danger auto-assign reviewers?

**Comment by jwu910** [comment]
Yeah let's take research some options

**Comment by rainrivas** [comment]
@jwu910 there an app built on probot that does auto-assignments -- https://probot.github.io/apps/auto-assign/

**Comment by rainrivas** [comment]
So I'm guessing I'm looking into this =D

**Comment by jwu910** [comment]
Lol thought you said you wanted to. I can pick it up =p

**Comment by rainrivas** [comment]
Nah it's cool. I got it. I'll play around on my fork and if it works you'll need to make changes on your end

**Comment by rainrivas** [comment]
So I'm trying to handle this using the bot but there appears to be some issues with it. See [auto-assign 46](https://github.com/kentaro-m/auto-assign/issues/46) and [auto-assign 38](https://github.com/kentaro-m/auto-assign/issues/38) which both report that the bot is not working at all or only working intermittently.

**Comment by jwu910** [comment]
https://github.com/jwu910/check-it-out/pull/298 Fixed here. Closing issue
