### ISSUE TITLE
Add a 'format' script to package.json

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#271]
We should have a format script that could be called with `npm run format` to run prettier on the project source files.

Prettier and eslint are already setup. I am not 100% sure `npm run lint:fix` script will actually fix everything prettier will.

**Comment by DonaldLika** [comment]
I can do it

**Comment by jwu910** [comment]
Let me know if you have any trouble. I should have all the dependencies installed.

**Comment by jwu910** [comment]
Thanks @DonaldLika . Merged #273
