### ISSUE TITLE
Terminal name remains as "Check It Out" after application has closed

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#296]
OS: Ubuntu 18.04

Remove screen title property from the interface

![cioerror](https://user-images.githubusercontent.com/12107969/51129348-18a31e80-17df-11e9-89f7-a849cc30d15b.gif)

Edit: Add gif

**Comment by ahlaw** [comment]
Does this issue occur every time? I could not reproduce the issue on Ubuntu 18.04.

**Comment by ahlaw** [comment]
I just tried it using bash and zsh on gnome terminal, urxvt and xterm, and could not reproduce the issue on any combination of those.

**Comment by jwu910** [comment]
Thanks for taking another look. I'll dig into it a little deeper if I get time tomorrow. I'll leave the issue open for now.

**Comment by jwu910** [comment]
@ahlaw I just attached a gif to the original issue post at the top.

I was on Antergos running the window manager i3 before, which is probably why I never saw this. I never had menu bars so it never came up. But I'll ask around and see if anyone else can reproduce as well.

**Comment by protoEvangelion** [comment]
@jwu910 I cannot repro on mac mojave with iterm or default terminal.

**Comment by antoniorhee** [comment]
On ubuntu 16.04 LTS and I can reproduce the issue. Upon exiting application the terminal title is still "Check It Out".

**Comment by jwu910** [comment]
Hmm. I think we can probably still just remove the title attribute from the application. It may be an issue with the Blessed library that we used to render the screen.

After looking at some other similar tools, I don't think its common practice to rewrite the window title anyways.
