### ISSUE TITLE
Add LGTM badge to README

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#310]
```
<a href="https://lgtm.com/projects/g/jwu910/check-it-out/alerts/"><img alt="Total alerts" src="https://img.shields.io/lgtm/alerts/g/jwu910/check-it-out.svg?logo=lgtm&logoWidth=18"/></a>
```

Using LGTM to track introduction of code smells and tech debt. Let's add the badge to the readme

**Comment by Lorsen** [comment]
Haven't contributed to Open Source before. I'm on a Windows computer - would it be an issue to add the badge?

**Comment by jwu910** [comment]
@Lorsen First of all, welcome to open source! I don't your operating system should be in issue here.

Give it a shot and let me know if you have any questions! Just take a look through the [contributing guidelines](https://github.com/jwu910/check-it-out/blob/master/CONTRIBUTING.md) =]

**Comment by Lorsen** [comment]
Is this button placement the desired output? 
![image](https://user-images.githubusercontent.com/6044039/52808299-2274a780-3053-11e9-91bc-d639f6ec1294.png)

**Comment by jwu910** [comment]
Looks fine to me! Shoot a PR over and I'll take a look. I figure more badges will get added over time, not particularly picky about the order they're added in

**Comment by jwu910** [comment]
Merged, Thanks @Lorsen 	!
