### ISSUE TITLE
Add CodeClimate's Maintainability badge to README

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#311]
```
<a href="https://codeclimate.com/github/jwu910/check-it-out/maintainability"><img src="https://api.codeclimate.com/v1/badges/e2d8564876becd663ff9/maintainability" /></a>
```

Using codeCoverage to keep track of this projects code maintainability, lets add the badge to our Readme.

**Comment by celesterobinson** [comment]
I can add this if that's alright :)

**Comment by jwu910** [comment]
@celesterobinson 	Sure thing! Let me know if you run into any issues.

**Comment by jwu910** [comment]
Merged, thanks!! @celesterobinson

**Comment by celesterobinson** [comment]
Thanks for letting me contribute!

**Comment by jwu910** [comment]
Welcome to open source @celesterobinson!
