### ISSUE TITLE
Fix "similar-code" issue in src/utils/interface.js

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#312]
Similar blocks of code found in 3 locations. Consider refactoring.

https://codeclimate.com/github/jwu910/check-it-out/src/utils/interface.js#issue_5c61a96c7c4f6f0001000030

If we can isolate similar "theme" styles for our interface objects, lets move that code into another variable to keep the code DRY.

**Comment by sog01** [comment]
May I try this ?

**Comment by jwu910** [comment]
@sog01 	Absolutely! Let me know if you run into any issues.

**Comment by sog01** [comment]
Nice, I will send a PR !

**Comment by jwu910** [comment]
Merged, thanks!
