### ISSUE TITLE
Fix "similar-code" issue in src/utils/git.js

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#313]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/jwu910/check-it-out/src/utils/git.js#issue_5c61a96c7c4f6f0001000032

Try to identify and consolidate code in git utils to keep code DRY

**Comment by celesterobinson** [comment]
Hey I'll work on this :)

**Comment by DominikPalacz** [comment]
Hey, i would love to tackle this one - let me know if you still need help with it. ( It is my first open source issue ) :)

**Comment by rn2293** [comment]
Hi, can I please raise a PR to resolve this issue?

**Comment by jwu910** [comment]
@rn2293 	Absolutely! Feel free to shoot me a PR, let me know if you have any questions or need any help

**Comment by jwu910** [comment]
Merged , thanks @rn2293 !
