### ISSUE TITLE
Sort branches by most recently checked out

### ISSUE THREAD

**Issue by protoEvangelion** [jwu910/check-it-out#33]
This is especially helpful when there are tons of branches and you don't want to have to scroll through the whole list to find the ones that you most commonly use

**Comment by jwu910** [comment]
This will have to wait until tabs are enabled. To minimize the work needed for this ticket, I think we can just sort the refs as we call them, but once I split up the remotes by tabs, the sorting will be simple.

Currently, if we sort the branches, the entire output is sorted so we mix up local and remotes.

**Comment by jwu910** [comment]
Fixed by #59
