### ISSUE TITLE
Contributing guidelines URL on http://checkit.club not working

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#370]
Our URL set up for the CONTRIBTUING guidelines should be forwarded to the current copy on the master branch. 

We should not be using a relative URL on https://checkit.club

**Comment by abhinavmasalia** [comment]
Hello, can I take this up? I have never worked on open source and would love to start.

**Comment by jwu910** [comment]
@abhinavmasalia Go for it! This should be a fairly simple issue. Please let me know if you have any questions

**Comment by abhinavmasalia** [comment]
@jwu910 I am done with the changes.

**Comment by abhinavmasalia** [comment]
@jwu910 I am done, could you review my submission?
