### ISSUE TITLE
Bug: Documentation of supported node versions

### ISSUE THREAD

**Issue by gvsvarun** [jwu910/check-it-out#397]
I see, the documentation website shows that node supports v4.0 and higher, but the babel is targeted for v6.0 and higher. I assume this should be either rectified in babel config or update the documentation accordingly.

Willing to work on this, on your advise accordingly.

**Comment by jwu910** [comment]
Thanks for seeing this. The documentation should be updated to reflect greater than or equal to node version 6.

You can take this issue if you’d like.

**Comment by gvsvarun** [comment]
I do want to, but it looks like an HTML change and I don't see the web page folder anywhere.

Would you mind letting me know if that is a different repo or some configuration I missed?

**Comment by jwu910** [comment]
The site is hosted off of my gh-pages branch

**Comment by gvsvarun** [comment]
Thanks for the reference. I have raised a PR for the same.

**Comment by gvsvarun** [comment]
Closing this issue as the PR has been merged.
