### ISSUE TITLE
Documentation: Fork me on Github button broken

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#437]
Expected: URL should point to `https://github.com/jwu910/check-it-out/fork`
Actual: URL points to `https://github.com/you`

Details:
branch: `gh-pages`
file: `index.html`

Live: http://checkit.club/

**Comment by arvind0598** [comment]
I could work on this. Should I?

**Comment by jwu910** [comment]
@arvind0598 It's open to anyone, if you get it done, just send the pull request and I can review.

Thanks!

**Comment by arvind0598** [comment]
Oh I didn't realize someone else fixed it already.

@jwu910, trying to visit http://checkit.club/ says "The page isn’t redirecting properly", you might wanna check that out.

**Comment by jwu910** [comment]
Thanks for the PR's @arvind0598 and @Tanuj69
