### ISSUE TITLE
Hotkey to copy highlighted branch name to clipboard

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#459]
As a user, I would like to be able to navigate through CIO, and press a hot key to copy the current highlighted branch name to my clipboard.

**Comment by mahendraHegde** [comment]
@jwu910  I'd like to work on it. 
I'm planning to use [copy-paste](https://www.npmjs.com/package/copy-paste) to write to clipboard. any other suggestions/thoughts?

**Comment by jwu910** [comment]
@mahendraHegde Thanks for taking interest in this! [clipboardy](https://github.com/sindresorhus/clipboardy) looks to have larger user-base. Could we take a look at trying clipboardy?

No particular suggestion for a hotkey, but we've followed vim style keys for use navigating. so we'll want to be mindful about "reserved" keys. Let me know if you have any questions.

Looking forward to seeing how we can get this implemented!

**Comment by jwu910** [comment]
Thanks for the PR @mahendraHegde . Just merged! https://github.com/jwu910/check-it-out/pull/

@all-contributors please add @mahendraHegde for code

**Comment by jwu910** [comment]
Thanks @mahendraHegde check out release [3.1.0](https://github.com/jwu910/check-it-out/releases/tag/v3.1.0)!

Thanks for your help! 

``` 
npm install --global check-it-out
``` 
to install the latest to start using it :rocket:
