### ISSUE TITLE
cio --version should have an extra line break after display version number

### ISSUE THREAD

**Issue by phuchle** [jwu910/check-it-out#460]
```
Phucs-MacBook-Pro-2:dashboard phuc$ cio --version
3.0.0Phucs-MacBook-Pro-2:dashboard phuc$ 
```

**Comment by jwu910** [comment]
Thanks for filing this. It is an issue with our logging.

We've been using `stdout.write` which outputs does not include native formatting. We should be able to fix this with a line break character at the end of the log.

**Comment by aksappy** [comment]
@jwu910 I have submitted a PR. Noticed that the issue is not occurring in windows, tested in mac and found to be true. Should we test this in linux? I don't have one running atm!

**Comment by jwu910** [comment]
@aksappy Thanks for the PR! 

We haven't had a chance to figure out windows compatibility so I would not worry about it. We've disclosed the incompatibility #127 and #128 -- I think our main dependency [blessed](https://github.com/chjj/blessed) doesnt work on windows.

Linux and Mac should behave the same as there shouldn't be any os specific functionality being used.

I'll review once I get a chance.

Thanks again!

**Comment by aksappy** [comment]
@jwu910 Pleasure.. the CI build has failed because of a `(file: string)` in `dangerfile.js` - [details](https://travis-ci.org/jwu910/check-it-out/jobs/609480132?utm_medium=notification&utm_source=github_status)
I know the reason, and it is not from my PR, trying to look at where it has come from..

**Comment by jwu910** [comment]
@aksappy I think we can ignore danger errors right now. I was trying to bump it up a major version and it was failing more than succeeding at the moment. As long as we’re building okay, we can continue forward.

I’ll review any new changes once I can
