### ISSUE TITLE
Change mentions of master to main in documentation

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#491]
## Description
Default branch was recently [changed](https://github.com/github/renaming) from `master` -> `main`.

We need to update our documentation to accurately represent this change so instructions for future contributions are clear.

**Comment by Jonesy22** [comment]
I'll create a PR for this 😄

**Comment by jwu910** [comment]
Thanks @Jonesy22 ! Let me know if you have any trouble

**Comment by CatherineNjenga** [comment]
Hello, I would love to help in making the changes if the issue is still open.

**Comment by jwu910** [comment]
Go for it! If you get a PR open, i can take a look. Thanks @CatherineNjenga !

**Comment by jwu910** [comment]
@CatherineNjenga https://hacktoberfest.com/ just started if you want to take a look at this again, i added the label to the issue, and since you were already working on it, wanted to see if you wanted to try to close out this PR

**Comment by JeremyTechDev** [comment]
Heeey @jwu910
I can work on this in case is needed, I see @CatherineNjenga has not been working on it for some time.

**Comment by jwu910** [comment]
Sure, you can pick up where @CatherineNjenga left off on their branch too, then at least both of you can get credit

**Comment by Jimmy-Vu** [comment]
Hi @jwu910,
There hasn't been progress made on this issue for a while now. I'll be happy to take over and wrap up this issue if that's fine with you

**Comment by jwu910** [comment]
Sure thing @Jimmy-Vu
