### ISSUE TITLE
Feat: Upgrade to TS ➕ 🦖 

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#492]
## Acknowledgement 🎉 
First of all, thanks for being here. This project has always been a close one to my heart. Many thanks in advance for any contributions that are made, whether they're issues, docs, code, or just fixing typos.

## Description :construction:
This can be the placeholder ticket for the migration. How I'm understanding this now is the first step being changing the `.js` extension to `.ts`. The NPM script for the TypeScript compiler was already setup on the branch `typescript-migration` which will serve as our main feature branch we can send PRs to.

## Developing :computer:
Since we'll have dual compilers until we finish, development scripts will probably include two scripts being run in two separate sessions: `npm run watch` and `npm run tsc -- --watch`.

## Testing 🐛 
After you're set up, you should be able to run `npm start` to test your local build. If you have a global installation of `check-it-out` that you want to use the local build for, you can run `npm link` (I believe) so your global `cio` binary should link to your local output files in this repo

## Contributing 🧗🏼 
Find the [project board](https://github.com/users/jwu910/projects/7/views/1) and pick a ticket. If there's more work that has been overlooked, or we need to break any files up into smaller tickets, lets create them accordingly.

**Comment by jwu910** [comment]
@kienD Couple points I wanted to check with. You had mentioned that with TS, we could drop all babel dependencies, right? Worth it?

**Comment by jwu910** [comment]
CC: @drewbrokke Had a random Idea this week to finally get some hands on practice with TS. If you're up for any reviews in the next couple months, I can tag you 🙏🏼 lmk if you're interested

**Comment by drewbrokke** [comment]
@jwu910 absolutely!

I actually played around with this idea a bit and have a suggestion: disable ESLint initially and just focus on getting the TS conversion done. Having two separate compilers bark at you can be a lot during the transition.

Once the TS side of things is up to snuff, re-introduce ES as if for the first time, since you'll have to change the config anyways to make it work with TS.

All this is ultimately up to you of course, this is just how I would approach it. Thoughts?

**Comment by kienD** [comment]
> @kienD Couple points I wanted to check with. You had mentioned that with TS, we could drop all babel dependencies, right? Worth it?

lol, it depends on what we use so I'll have to look into it.

**Comment by jwu910** [comment]
@drewbrokke sweet that sounds like a plan. I'll put up an issue later for the Eslint removal and when we turn it back on later anyways, we can use that opportunity to upgrade the packages

**Comment by jwu910** [comment]
#509 Mentioning this issue here, looks like tsconfig may have been missed. need to visit at some point

**Comment by drewbrokke** [comment]
@jwu910 I'm doing great, thanks! I went ahead and sent a pull for this (#531), take a look whenever you have time. Hope you're doing well! Let me know if I can help with anything else 👍

**Comment by jwu910** [comment]
@drewbrokke i think your PR might have just completed the rest of the TS work. Opened up a PR into main, did some house keeping, and going to continue doing some testing, but so far, i think the diff from main is conflict free atm 🙏🏻
