### ISSUE TITLE
Remove ESLint from project

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#501]
## Description

This [comment](https://github.com/jwu910/check-it-out/issues/492#issuecomment-1126035961) provides an interesting point to removing ESLint during the TS migration to prevent two linters from clashing.

We can remove ESLint for now (remove dependencies and remove configuration files), and post migration, we can re-install an updated ESLint with the correct configurations for TypeScript support.

**Comment by a-camarillo** [comment]
Hello @jwu910, I'd like to work on this.

**Comment by jwu910** [comment]
Ah perfect, thanks. now you have interacted, i can assign you
