### ISSUE TITLE
Update README to tell developers to use npm start

### ISSUE THREAD

**Issue by rahulk94** [jwu910/check-it-out#532]
Update README to tell developers to use `npm start` so that we don't need to maintain both when we add changes to it during the typescript migration (and also if the command ever changes)

Raised off the back of https://github.com/jwu910/check-it-out/pull/531#discussion_r1224848309

**Comment by jwu910** [comment]
Hey @rahulk94 thanks for raising concerns with this. I took a look at this with a little more detail and don't see an issue offering users to call the build assets directly or with npm's `start` alias. Going to close this for now.
