### ISSUE TITLE
New published package broken

### ISSUE THREAD

**Issue by jwu910** [jwu910/check-it-out#537]
## Description
Installing new check-it-out globally is throwing an esm error. This one seems a little harder to reproduce, and not entirely sure if I am able to see this within my local repo. Wondering if we are missing some files in the tarball that ships with the release...

Need to investigate quickly and/or unpublish 4+ until we can get a fix out for this.

## Steps to repro
```
npm i -g check-it-out
cio -v
```

CC: @drewbrokke if you have any ideas, this would be great.

```
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: ENOENT: no such file or directory, open 'package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'package.json'
}
```

**Comment by jwu910** [comment]
I've been testing on multiple versions of node at the moment. I'm suspecting this is coming from changes/introduction to config.ts and the top level `await` for `fs.readFile`

**Comment by jwu910** [comment]
https://stackoverflow.com/questions/41123631/how-to-get-the-version-from-the-package-json-in-typescript

Seeing this answer, feels like a pretty solid way to go to avoid the need for the promise to read the file at run time. I've always wanted to find a way to just have the js implementation of a static string that gets updated at some point, might put up a PR to consider something like this.

**Comment by drewbrokke** [comment]
@jwu910 I'm not able to reproduce the issue. Is the `package.json` file present in the installed package? Also, since I removed the usage of `__dirname` (and if that is the cause of the issue), we could look at restoring it using [this suggestion](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#what-do-i-use-instead-of-__dirname-and-__filename) from the ESM guide I was following.

**Comment by drewbrokke** [comment]
@jwu910 ok I could reproduce and it looks like the `package.json` file is present. We just need to update our read paths in `config.ts` to something like this: 
```ts
const filePath = new URL('../../package.json', import.meta.url);

export const packageJson = JSON.parse(await fs.readFile(filePath, { encoding: "utf-8" }));
```

**Comment by jwu910** [comment]
I was able to get around the issue with the last release! Though it was more so the quickest way i coudl find atm

https://github.com/jwu910/check-it-out/pull/538/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R70-R72

https://github.com/jwu910/check-it-out/pull/538/files#diff-841254fe75488c1bd4cd7f68f00b4be0e48dcfbc4a16b45847b68295e0e3b27b

These changes show the direction i went. had to figure out the build step to leverage udpating the file, which is just a work around we can undo later if we can get this working.
