### ISSUE TITLE
[Bug] image is not rendered.

### ISSUE THREAD

**Issue by Himanshuch8055** [jwu910/check-it-out#545]
The (fork me on Github) image is not rendered on the web page.

![image](https://github.com/jwu910/check-it-out/assets/94627200/33069ea9-217c-4c0b-8418-22c27f3004b1)

**Comment by jwu910** [comment]
Thanks for pointing this out @Himanshuch8055, i put up a fix

**Comment by jwu910** [comment]
@all-contributors please add @Himanshuch8055 for bug
