### ISSUE TITLE
Redesign the website

### ISSUE THREAD

**Issue by AndersonCeci** [jwu910/check-it-out#546]
Hello,
I recently came across your project and I'm interested to try and redesigning your website. 
Could you please let me know if the project is still active? 
Because your website looks a little outdated.

**Comment by jwu910** [comment]
Hi @AndersonCeci thanks for reaching out and your expressed interested in a website redesign. This project is mostly in maintenance mode with few changes here and there. There aren't any current major plans for a revamp or major release that could warrant a refresh at this time.

Thanks!
