### ISSUE TITLE
"Remote" heading doesn't handle branches that are grouped

### ISSUE THREAD

**Issue by rainrivas** [jwu910/check-it-out#56]
Branches that are grouped inside of a remote get mis-labeled as having their group be the remote
e.g
```
remote: origin
branch: hotfix/fix-print-out
```
since hotfix is a grouping, it would show up as `origin/hotfix/fix-print-out`; therefore all "hotfix" branches get marked as having hotfix for a remote
![image](https://user-images.githubusercontent.com/12107963/37743013-59c22744-2d25-11e8-9296-6d26362fb5c1.png)

I'm guessing these lines (or close to it) are the culprits https://github.com/jwu910/check-it-out/blob/0b3a1b1f505b93979b1c380f2b63de2f4a124543/index.js#L53-L55

**Comment by jwu910** [comment]
https://github.com/jwu910/check-it-out/blob/master/src/utils/git.js#L128 

Is the new culprit. 

Figuring out a fix for this now.
